{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a785f71-3bb2-4088-8cb1-a74cecb72785",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "\n",
    "# -----------------------------\n",
    "# Sample / Dummy Data\n",
    "# -----------------------------\n",
    "data = [\n",
    "    {\n",
    "        \"Name\": \"Gagan Kapoor\",\n",
    "        \"Title\": \"Data Scientist\",\n",
    "        \"Company\": \"Google\",\n",
    "        \"Person_Location\": \"Gurugram, Haryana, India\",\n",
    "        \"Company_HQ\": \"Mountain View, California\",\n",
    "        \"Work_Mode\": \"Remote\",\n",
    "        \"Email\": \"gagankapoor@gmail.com\",\n",
    "        \"LinkedIn\": \"https://www.linkedin.com/in/gagan-kapoor-5621141a5/\"\n",
    "    },\n",
    "    {\n",
    "        \"Name\": \"Kanishk Gupta\",\n",
    "        \"Title\": \"Software Engineer 2\",\n",
    "        \"Company\": \"Microsoft\",\n",
    "        \"Person_Location\": \"West Delhi, Delhi, India\",\n",
    "        \"Company_HQ\": \"WA 98052, USA\",\n",
    "        \"Work_Mode\": \"Remote\",\n",
    "        \"Email\": \"KanishkGupta@gmail.com\",\n",
    "        \"LinkedIn\": \"https://www.linkedin.com/in/kanishkgupta2000/\"\n",
    "    },\n",
    "    {\n",
    "        \"Name\": \"Liang Cao\",\n",
    "        \"Title\": \"Senior Software Engineer\",\n",
    "        \"Company\": \"Meta\",\n",
    "        \"Person_Location\": \"Seattle, Washington, United States\",\n",
    "        \"Company_HQ\": \"Menlo Park, California\",\n",
    "        \"Work_Mode\": \"Hybrid\",\n",
    "        \"Email\": \"LiangCao@gmail.com\",\n",
    "        \"LinkedIn\": \"https://www.linkedin.com/in/liang-cao-060727251/\"\n",
    "    },\n",
    "    {\n",
    "        \"Name\": \"Jayant Sohane\",\n",
    "        \"Title\": \"Full-Stack Developer\",\n",
    "        \"Company\": \"Tesla\",\n",
    "        \"Person_Location\": \"San Francisco Bay Area\",\n",
    "        \"Company_HQ\": \"Austin, Texas, United States\",\n",
    "        \"Work_Mode\": \"Remote\",\n",
    "        \"Email\": \"JayantSohane@gmail.com\",\n",
    "        \"LinkedIn\": \"https://www.linkedin.com/in/jayant-sohane/\"\n",
    "    },\n",
    "    {\n",
    "        \"Name\": \"Snehil Srivastava\",\n",
    "        \"Title\": \"Data Engineer\",\n",
    "        \"Company\": \"Amazon\",\n",
    "        \"Person_Location\": \"Gurugram, Haryana, India\",\n",
    "        \"Company_HQ\": \"Seattle, Washington\",\n",
    "        \"Work_Mode\": \"Remote\",\n",
    "        \"Email\": \"SnehilSrivastava@gmail.com\",\n",
    "        \"LinkedIn\": \"https://www.linkedin.com/in/snehil-srivastava-42315b173/\"\n",
    "    }\n",
    "]\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "\n",
    "# -----------------------------\n",
    "# Scoring Weights (Config)\n",
    "# -----------------------------\n",
    "WEIGHTS = {\n",
    "    \"senior_role\": 30,\n",
    "    \"mid_role\": 20,\n",
    "    \"big_tech_company\": 30,\n",
    "    \"india_location\": 10,\n",
    "    \"us_hub_location\": 20,\n",
    "    \"remote\": 20,\n",
    "    \"hybrid\": 10\n",
    "}\n",
    "\n",
    "BIG_TECH = [\"google\", \"microsoft\", \"meta\", \"amazon\", \"tesla\"]\n",
    "US_HUBS = [\"bay area\", \"san francisco\", \"seattle\", \"austin\"]\n",
    "\n",
    "# -----------------------------\n",
    "# Scoring Function\n",
    "# -----------------------------\n",
    "def calculate_score(row):\n",
    "    score = 0\n",
    "\n",
    "    title = row[\"Title\"].lower()\n",
    "    location = row[\"Person_Location\"].lower()\n",
    "    company = row[\"Company\"].lower()\n",
    "    work_mode = row[\"Work_Mode\"].lower()\n",
    "\n",
    "    # Role seniority\n",
    "    if \"senior\" in title:\n",
    "        score += WEIGHTS[\"senior_role\"]\n",
    "    elif any(x in title for x in [\"engineer\", \"scientist\", \"developer\"]):\n",
    "        score += WEIGHTS[\"mid_role\"]\n",
    "\n",
    "    # Company strength\n",
    "    if company in BIG_TECH:\n",
    "        score += WEIGHTS[\"big_tech_company\"]\n",
    "\n",
    "    # Location scoring\n",
    "    if any(hub in location for hub in US_HUBS):\n",
    "        score += WEIGHTS[\"us_hub_location\"]\n",
    "    elif \"india\" in location:\n",
    "        score += WEIGHTS[\"india_location\"]\n",
    "\n",
    "    # Work mode\n",
    "    if work_mode == \"remote\":\n",
    "        score += WEIGHTS[\"remote\"]\n",
    "    elif work_mode == \"hybrid\":\n",
    "        score += WEIGHTS[\"hybrid\"]\n",
    "\n",
    "    return min(score, 100)\n",
    "\n",
    "\n",
    "# Apply scoring\n",
    "df[\"Probability_Score\"] = df.apply(calculate_score, axis=1)\n",
    "\n",
    "# Rank\n",
    "df = df.sort_values(by=\"Probability_Score\", ascending=False)\n",
    "df.insert(0, \"Rank\", range(1, len(df) + 1))\n",
    "\n",
    "# -----------------------------\n",
    "# Streamlit UI\n",
    "# -----------------------------\n",
    "st.set_page_config(page_title=\"Lead Ranking & Scoring Dashboard\", layout=\"wide\")\n",
    "\n",
    "st.title(\"📊 Tech Professional Lead Ranking & Scoring Dashboard\")\n",
    "st.write(\n",
    "    \"This mini-dashboard demonstrates how professional leads can be identified, enriched, and ranked using transparent, configurable business criteria such as role seniority, company tier, location, and work mode.\"\n",
    ")\n",
    "\n",
    "# Search Filter\n",
    "search_term = st.text_input(\"Search by Name, Location, Company, or Title\")\n",
    "\n",
    "if search_term:\n",
    "    filtered_df = df[df.apply(lambda row: search_term.lower() in row.astype(str).str.lower().to_string(), axis=1)]\n",
    "else:\n",
    "    filtered_df = df\n",
    "\n",
    "# Display Table\n",
    "st.dataframe(filtered_df, use_container_width=True)\n",
    "\n",
    "# Download Button\n",
    "csv = filtered_df.to_csv(index=False).encode('utf-8')\n",
    "st.download_button(\n",
    "    label=\"Download CSV\",\n",
    "    data=csv,\n",
    "    file_name=\"lead_scoring_results.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "st.caption(\"Demo built using Python + Streamlit with dummy data and transparent scoring logic.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e30bb01-1ce0-4867-9d1e-6d19c2d10529",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
